defaults:
  project_id: "PVT_kwHOAOKHl84BHgin"
  target_repo: "Rindrics/recurring-backlog-item-creator"
issues:
  - name: "Wash My Cat"
    template_file: ".github/ISSUE_TEMPLATE/wash_my_cat.md"
    creation_months: [1, 3, 5, 7, 9, 11]
    title_suffix: "- {{YearMonth}}"
    fields:
      Priority: "P1"
      Status: "Ready"
  - name: "Buy New Shoes"
    template_file: ".github/ISSUE_TEMPLATE/buy_shoes.md"
    title_suffix: "- ({{Year}})"
    creation_months: [3, 12]
    fields:
      Priority: "P2"
      Status: "Backlog"
    project_id: "PVT_kwHOAOKHl84BHgin"  # you can override the default project_id
    target_repo: "Rindrics/recurring-backlog-item-creator"  # you can override the default target_repo
