defaults:
  project_id: "PVT_kwHOAOKHl84BHgin"
  target_repo: "Rindrics/gh-issue-config-filter"
issues:
  - name: "Wash My Cat"
    template_file: ".github/ISSUE_TEMPLATE/wash_my_cat.md"
    creation_months: [1, 3, 5, 7, 9, 11]
    title_suffix: "- $(date +%Y-%m)"
    fields:
      priority: "1"
      status: "Ready"
  - name: "Buy New Shoes"
    template_file: ".github/ISSUE_TEMPLATE/buy_shoes.md"
    title_suffix: "- $(date +%Y)"
    creation_months: [3, 12]
    fields:
      priority: "2"
      status: "Backlog"
    project_id: "other_project_id"
    target_repo: "other/repo"
